kind: pipeline
type: kubernetes
#type: docker
name: dev

steps:
  - name: git
    image: wuzhixiang/awscli
    commands:
      - ./deploy.sh

trigger:
  branch:
  - master
  event:
  - custom
  - push
  - pull_request
