kind: pipeline
type: kubernetes
#type: docker
name: dev

steps:
  - name: git
    image: wuzhixiang/awscli
    commands:
      - git ls-tree -r --name-only HEAD | while read filename; do \
      - unixtime=$(git log -1 --format="%at" -- "${filename}") \
      - echo -t ${touchtime} "${filename}" \
      - done

trigger:
  branch:
  - master
  event:
  - custom
  - push
  - pull_request
